# Introduction to numpy

numpy = numerical python

This material is inspired from different source:

* https://github.com/SciTools/courses
* https://github.com/paris-saclay-cds/python-workshop/blob/master/Day_1_Scientific_Python/01-numpy-introduction.ipynb

This notebook was designed by Dr. Guillaume Lemaitre

### What is NumPy?

* memory-efficient container for multi-dimensional homogeneous (mainly numerical) data (NumPy array)
* fast vectorised operations on arrays
* library general purpose functions: data reading/writing, linear algebra, FFT etc. 
* main applications: signal processing, image processing, analysis of raw data from measurment instruments

### Difference between python list and numpy array

Python offers some data containers to store data. Lists are generally used since they allow for flexibility.

In [1]:
# listcomprehension
x = [i for i in range(10)]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

At a first glance, numpy array seems to offer the same capabilities.

In [6]:
import numpy as np

In [11]:
x = np.arange(10)
x

# perhatikan, bahwa muncul term 'array' pada penggunaan np.arange()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x.dtype

dtype('int32')

In [14]:
# mengubah tipe array int ke dalam 64 bit
x = np.arange(10, dtype=np.int64)
x



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

To find the difference, we need to focus on the low-level implementation of these two containers.

A python list is a contiguous array in memory containing the references to the stored object. 
It allows for instance to store different data type object within the same list.

In [15]:
x = [1, 2.0, 'three']
x

[1, 2.0, 'three']

In [32]:
np.array([1, 2.0, 'three'], dtype =np.object)

array([1, 2.0, 'three'], dtype=object)

In [18]:
print('The type of x is: {}'.format(x))
for idx, elt in enumerate(x):
    print('The type of the {}-ith element is" {}'.format(idx, type(elt)))

The type of x is: [1, 2.0, 'three']
The type of the 0-ith element is" <class 'int'>
The type of the 1-ith element is" <class 'float'>
The type of the 2-ith element is" <class 'str'>


### Numpy arrays, however, are directly storing the typed-data. Therefore, they are not meant to be used with mix type.

In [18]:
x = np.arange(3)
print('The type of x is: {}'.format(type(x)))
print('The data type of x is: {}'.format(x.dtype))

The type of x is: <class 'numpy.ndarray'>
The data type of x is: int64


### Create numpy array

Try out some of these ways of creating NumPy arrays. See if you can produce:

* a NumPy array from a list of numbers,
* a 3-dimensional NumPy array filled with a constant value -- either 0 or 1,
* a NumPy array filled with a constant value -- not 0 or 1. (Hint: this can be achieved using the last array you created, or you could use np.empty and find a way of filling the array with a constant value),
* a NumPy array of 8 elements with a range of values starting from 0 and a spacing of 3 between each element, and
* a NumPy array of 10 elements that are logarithmically spaced.


In [12]:
y = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
y_np = np.array(y)
y_np


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
y_np.dtype

dtype('int64')

In [24]:
y = [0, 1, 2.5, 3, 4, 5, 6, 7, 8, 9]
y_np = np.array(y)
y_np.dtype

dtype('float64')

In [27]:
#a 3-dimensional NumPy array filled with a constant value -- either 0 or 1,
X = np.zeros((2,3,5)) # x, y, z
X

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [28]:
X.shape

(2, 3, 5)

In [24]:
# a NumPy array filled with a constant value -- not 0 or 1.
X = np.ones((2,3,5)) * 3
X

array([[[ 3.,  3.,  3.,  3.,  3.],
        [ 3.,  3.,  3.,  3.,  3.],
        [ 3.,  3.,  3.,  3.,  3.]],

       [[ 3.,  3.,  3.,  3.,  3.],
        [ 3.,  3.,  3.,  3.,  3.],
        [ 3.,  3.,  3.,  3.,  3.]]])

In [25]:
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        for k in range(X.shape[2]):
            X[i,j,k] = 5

In [26]:
X

array([[[ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.]],

       [[ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.]]])

In [33]:
#ambil komponen dari array
# start; stop; step
y_np3=np.arange(0,8,3)
print(y_np3)

[0 3 6]


In [34]:
np.linspace(0, 10, num=10, endpoint = False)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [37]:
np.logspace(1,100,num=10)

array([1.e+001, 1.e+012, 1.e+023, 1.e+034, 1.e+045, 1.e+056, 1.e+067,
       1.e+078, 1.e+089, 1.e+100])

In [35]:
X=np.ones(8)
X

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

How could you change the shape of the 8-element array you created previously to have shape (2, 2, 2)? Hint: this can be done without creating a new array.

In [36]:
X_new=np.reshape(X, (2,2,2))
X_new

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])

### Indexing

Note that the NumPy arrays are zero-indexed:

In [74]:
data = np.random.randn(10000, 5)

In [75]:
data.shape

(10000, 5)

In [76]:
data

array([[ 0.52948246,  0.58318775,  1.76409927,  0.78493224, -0.15269185],
       [ 0.8271607 ,  0.00418193, -0.04469064,  1.07114899,  2.16079203],
       [ 1.00175107, -0.22012566, -0.02133788,  0.15515516,  0.3639165 ],
       ..., 
       [ 1.43916945,  0.79016407, -0.38687267, -0.07683913, -0.82112765],
       [ 1.00890128, -0.45444848, -1.56417924,  0.60413184, -1.31234187],
       [-0.0781389 ,  1.62742392,  0.80211904, -0.61955197, -1.40279486]])

In [77]:
data[0, 0]

0.52948246387824238

It means that that the third element in the first row has an index of [0, 2]:

In [78]:
data[0, 2]

1.7640992683050323

We can also assign the element with a new value:

In [79]:
data[0, 2] = 100.
print(data[0, 2])

100.0


NumPy (and Python in general) checks the bounds of the array:

In [80]:
print(data.shape)
data[60, 10]

(10000, 5)


IndexError: index 10 is out of bounds for axis 1 with size 5

Finally, we can ask for several elements at once:

In [81]:
# first row; first & third column
data[0, [0, 3]]

array([ 0.52948246,  0.78493224])

In [82]:
#all komponen in the first row
data[0,:]

array([   0.52948246,    0.58318775,  100.        ,    0.78493224,
         -0.15269185])

You can even pass a negative index. It will go from the end of the array.

In [83]:
data[-1, -1]

-1.4027948598068465

In [84]:
data[data.shape[0] - 1, data.shape[1] - 1]

-1.4027948598068465

### Slices

In [85]:
data[0:]

array([[  5.29482464e-01,   5.83187751e-01,   1.00000000e+02,
          7.84932237e-01,  -1.52691846e-01],
       [  8.27160696e-01,   4.18192716e-03,  -4.46906353e-02,
          1.07114899e+00,   2.16079203e+00],
       [  1.00175107e+00,  -2.20125662e-01,  -2.13378790e-02,
          1.55155160e-01,   3.63916504e-01],
       ..., 
       [  1.43916945e+00,   7.90164068e-01,  -3.86872670e-01,
         -7.68391306e-02,  -8.21127648e-01],
       [  1.00890128e+00,  -4.54448480e-01,  -1.56417924e+00,
          6.04131835e-01,  -1.31234187e+00],
       [ -7.81388980e-02,   1.62742392e+00,   8.02119040e-01,
         -6.19551968e-01,  -1.40279486e+00]])

In [86]:
data

array([[  5.29482464e-01,   5.83187751e-01,   1.00000000e+02,
          7.84932237e-01,  -1.52691846e-01],
       [  8.27160696e-01,   4.18192716e-03,  -4.46906353e-02,
          1.07114899e+00,   2.16079203e+00],
       [  1.00175107e+00,  -2.20125662e-01,  -2.13378790e-02,
          1.55155160e-01,   3.63916504e-01],
       ..., 
       [  1.43916945e+00,   7.90164068e-01,  -3.86872670e-01,
         -7.68391306e-02,  -8.21127648e-01],
       [  1.00890128e+00,  -4.54448480e-01,  -1.56417924e+00,
          6.04131835e-01,  -1.31234187e+00],
       [ -7.81388980e-02,   1.62742392e+00,   8.02119040e-01,
         -6.19551968e-01,  -1.40279486e+00]])

You can select ranges of elements using slices. To select first two columns from the first row, you can use:

In [87]:
data[0, 0:2]

array([ 0.52948246,  0.58318775])

Note that the returned array does not include third column (with index 2).

You can skip the first or last index (which means, take the values from the beginning or to the end):

In [88]:
# just return the same 

data[0, :2]

array([ 0.52948246,  0.58318775])

If you omit both indices in the slice leaving out only the colon (:), you will get all columns of this row:

In [89]:
data[0, :]

array([   0.52948246,    0.58318775,  100.        ,    0.78493224,
         -0.15269185])

In [90]:
# row: 6 to 11
# column: 5 to 7

# Why only return one colum?

data[5:10,4:6]

array([[-1.44194085],
       [-0.18625943],
       [-0.27511121],
       [-0.47864625],
       [ 0.42705962]])

### Filtering data

In [91]:
data

array([[  5.29482464e-01,   5.83187751e-01,   1.00000000e+02,
          7.84932237e-01,  -1.52691846e-01],
       [  8.27160696e-01,   4.18192716e-03,  -4.46906353e-02,
          1.07114899e+00,   2.16079203e+00],
       [  1.00175107e+00,  -2.20125662e-01,  -2.13378790e-02,
          1.55155160e-01,   3.63916504e-01],
       ..., 
       [  1.43916945e+00,   7.90164068e-01,  -3.86872670e-01,
         -7.68391306e-02,  -8.21127648e-01],
       [  1.00890128e+00,  -4.54448480e-01,  -1.56417924e+00,
          6.04131835e-01,  -1.31234187e+00],
       [ -7.81388980e-02,   1.62742392e+00,   8.02119040e-01,
         -6.19551968e-01,  -1.40279486e+00]])

We can produce a boolean array when using comparison operators.

In [92]:
data > 0

array([[ True,  True,  True,  True, False],
       [ True,  True, False,  True,  True],
       [ True, False, False,  True,  True],
       ..., 
       [ True,  True, False, False, False],
       [ True, False, False,  True, False],
       [False,  True,  True, False, False]], dtype=bool)

In [71]:
data[data > 0]
data

array([[        inf,         inf,         inf, -0.90731204, -0.60869981],
       [        inf,         inf, -1.56803863,         inf,         inf],
       [        inf, -2.22760019, -0.68225274, -2.14452059,         inf],
       ..., 
       [-0.93365254,         inf, -0.36896878,         inf,         inf],
       [-1.14122779,         inf,         inf,         inf,         inf],
       [        inf, -0.24636057,         inf, -0.05052232, -0.0825617 ]])

In [93]:
data[data > 0]

array([   0.52948246,    0.58318775,  100.        , ...,    0.60413184,
          1.62742392,    0.80211904])

This mask can be used to select some specific data.

In [94]:
data[data > 0]

array([   0.52948246,    0.58318775,  100.        , ...,    0.60413184,
          1.62742392,    0.80211904])

It can also be used to affect some new values

In [95]:
data[data > 0] = np.inf
data

array([[        inf,         inf,         inf,         inf, -0.15269185],
       [        inf,         inf, -0.04469064,         inf,         inf],
       [        inf, -0.22012566, -0.02133788,         inf,         inf],
       ..., 
       [        inf,         inf, -0.38687267, -0.07683913, -0.82112765],
       [        inf, -0.45444848, -1.56417924,         inf, -1.31234187],
       [-0.0781389 ,         inf,         inf, -0.61955197, -1.40279486]])

### Exercise


Answer the following quizz:

* Print the element in the $1^{st}$ row and $10^{th}$ cloumn of the data.
* Print the elements in the $3^{rd}$ row and columns of $3^{rd}$ and $15^{th}$.
* Print the elements in the $4^{th}$ row and columns from $3^{rd}$ t0 $15^{th}$.
* Print all the elements in column $15$ which their value is above 0.

In [45]:
import numpy as np

data = np.random.randn(10, 15)

data

array([[ 0.04515926, -0.57645593,  0.92051361,  0.36343589,  2.48398517,
        -2.95126149, -1.38455816,  0.49273788,  0.34158561, -0.23323758,
        -0.93923918,  0.70619593, -0.28148314, -0.94197661,  0.88326747],
       [ 0.17881262,  0.23764437,  0.5332213 , -1.32336276, -0.30546315,
        -0.82428259,  2.1052525 , -0.71089422, -1.42136443, -0.14400955,
         0.96900376,  0.27223477, -0.1604777 , -0.69001223,  0.86484275],
       [ 0.80572497,  0.1305035 , -0.66833106, -0.67855823, -2.2256704 ,
        -1.7408654 ,  0.43421115, -0.00502567, -0.7228895 , -0.01153184,
         1.51215402, -2.15969243,  0.26673928,  1.2867511 , -0.77250484],
       [-0.26048351,  0.09720227,  1.27502572, -0.54739355,  1.01276138,
         1.52897961,  0.76910923,  0.59812342, -0.96117194, -1.76828101,
        -0.17320273,  0.78234357, -1.41862069, -1.28278534, -0.3768426 ],
       [-0.64049119,  0.13463613,  0.70560057,  0.74323107, -0.55426212,
         0.1892281 ,  1.45085144,  1.41775617, 

In [38]:
data[0, 9]

0.15102983166502337

In [47]:
print(data[2, 2])
print(data[2, 14])

-0.6683310613415929
-0.7725048388614911


In [40]:
data[3, 2:]

array([ 0.33660776, -1.44338523, -1.55000909, -0.05898432, -0.93267859,
       -0.25306365, -0.68645742, -1.66386012,  0.3084164 ,  0.86781361,
        1.86189104,  0.69508398,  1.00420123])

In [48]:
row15 = data[:, 14]
print(row15[row15 > 0])

[0.88326747 0.86484275 0.94726303 0.48798409]


### Broadcasting

Broadcasting applies these three rules:

* If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.

* If the shape of the two arrays does not match in any dimension, either array with shape equal to 1 in a given dimension is stretched to match the other shape.

* If in any dimension the sizes disagree and neither has shape equal to 1, an error is raised.

Note that all of this happens without ever actually creating the expanded arrays in memory! This broadcasting behavior is in practice enormously powerful, especially given that when NumPy broadcasts to create new dimensions or to 'stretch' existing ones, it doesn't actually duplicate the data. In the example above the operation is carried out as if the scalar 1.5 was a 1D array with 1.5 in all of its entries, but no actual array is ever created. This can save lots of memory in cases when the arrays in question are large. As such this can have significant performance implications.

<img src="broadcasting.png">

Replicate the above exercises. In addition, how would you make the matrix multiplication between 2 matrices.

In [49]:
X = np.random.random((1, 3))
Y = np.random.random((3, 5))

In [50]:
print(X)

[[0.45036766 0.52709812 0.14026267]]


In [51]:
print(Y)

[[0.36137879 0.84285404 0.79571783 0.1611115  0.16534565]
 [0.15505846 0.32818575 0.27553253 0.30186958 0.24104119]
 [0.09606842 0.24596903 0.58003024 0.99033776 0.703792  ]]


kode berikut akan error

In [52]:
X * Y

ValueError: operands could not be broadcast together with shapes (1,3) (3,5) 

In [53]:
Z = np.dot(X, Y)
print(Z)

[[0.25795916 0.58708057 0.58495484 0.37058172 0.30023444]]


In [91]:
Z.shape

(1, 5)

### Views on Arrays

NumPy attempts to not make copies of arrays. 
Many NumPy operations will produce a reference to an existing array, known as a "view", instead of making a whole new array. 
For example, indexing and reshaping provide a view of the same memory wherever possible.


In [93]:
arr = np.arange(8)
arr_view = arr.reshape(2, 4)

# Print the "view" array from reshape.
print('Before\n', arr_view)


Before
 [[0 1 2 3]
 [4 5 6 7]]


In [94]:


# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print('After\n', arr_view)

After
 [[1000    1    2    3]
 [   4    5    6    7]]


In [95]:
arr = np.arange(8)
arr_view = arr.reshape(2, 4)

# Print the "view" array from reshape.
print('Before\n', arr_view)

# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print('After\n', arr_view)

Before
 [[0 1 2 3]
 [4 5 6 7]]
After
 [[1000    1    2    3]
 [   4    5    6    7]]


What this means is that if one array (`arr`) is modified, the other (`arr_view`) will also be updated : the same memory is being shared. This is a valuable tool which enables the system memory overhead to be managed, which is particularly useful when handling lots of large arrays. The lack of copying allows for very efficient vectorized operations.

Remember, this behaviour is automatic in most of NumPy, so it requires some consideration in your code, it can lead to some bugs that are hard to track down. For example, if you are changing some elements of an array that you are using elsewhere, you may want to explicitly copy that array before making changes. If in doubt, you can always copy the data to a different block of memory with the copy() method.

For example:

In [97]:
# kedua array akan berubah !!

arr = np.arange(8)
arr_view = arr.reshape(2, 4).copy()

# Print the "view" array from reshape.
print('Before\n', arr_view)

# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print('After\n', arr)

Before
 [[0 1 2 3]
 [4 5 6 7]]
After
 [1000    1    2    3    4    5    6    7]


### Exercise


#### Part 1

Create two arrays $x$
and $y$, where $x$ is a linearly spaced array in the interval $[0,3]$ of length 3000, and y represents the function $f(x)=x^2$ sampled at $x$

#### Part 2

Use indexing (not a for loop) to find the 10 values representing $y_i+y_{i−1}$
for i between 1 and 11.

Hint: What indexing would be needed to get all but the last element of the 1d array `y`. Similarly what indexing would be needed to get all but the first element of a 1d array.

#### Part 3

Write a function `trapz(x, y)`, that applies the trapezoid formula to pre-computed values, where x and y are 1-d arrays. The function should not use a for loop.

#### Part 4

Verify that your function is correct by using the arrays created in #1 as input to trapz. Your answer should be a close approximation of $\sum 30 x^2$ which is 9

#### Part 5 (extension)

`numpy` and `scipy.integrate` provide many common integration schemes. Find the documentation for NumPy's own version of the trapezoidal integration scheme and check its result with your own.

In [70]:
import numpy as np

x = np.random.randint(3, size=3000)
x

array([0, 2, 1, ..., 0, 0, 1])